---
title: "Notes on Ergodicity in Decision Making"
date: "2026-09-17"
author: "Your Name"
categories: [Analysis]
reference-location: margin
abstract: "Some notes on applications of ergodicity in decision making. Based initially on superficial exposure, and is now a practice of penance trying to formalize my thoughts and concepts aleady established."
---


# Introduction

Fundamentally, agents must act in and react to the environment they inhabit. If in this the system dynamics of scale matter, they should accordingly take action in a way that differentiate between scales; if time matters they choose their actions under the precedence that they must live or die in time. This is rudimentary, and the models (and actions) of in this context need to be coherent with this.

This is not what standard Economics does explicitly, but it is what it envisioned. Ergodicity Economics is one attempt to clarify this goal, in studying actors under varying dynamics and proscribing model frameworks (for the part that is an experimental and not just formal science) which account especially for inherent temporal components.

# Path-wise Dynamics

## Ensembles vs. Paths

To provide context we will discuss briefly the difference between ensembles and paths.
Consider the simple random walk $(\Sigma_1,\Sigma_2,\dots)$, with $\Sigma_n \sum_{i=1}^n S_i$ where $S_i$ is either $-1$ or $1$ with equal probability.
An ensemble, or population, refers to a set of resamples of a random varibles, i.e. $(\Sigma_n^{(1)},\Sigma_n^{(2)},\dots, \Sigma_n^{(m)})$ such that each $\Sigma_n^{(j)}$ for $j\in[m]$ marginally has the same distribution.

These $\Sigma_n^{(j)}$ need not be independent, ensembles often just refer to a "sample" of random variables that are exchangeable.
Specifically we assume that the distribution of the sample vector is invariant under any permutation $\pi$ of $[m]$
$$
\begin{equation*}
  (\Sigma_n^{(1)},\Sigma_n^{(2)},\dots, \Sigma_n^{(m)}) \deq (\Sigma_n^{(\pi(1))},\Sigma_n^{(\pi(2))},\dots, \Sigma_n^{(\pi(m))})\doteq\cbr{\Sigma_n^{(j)}}_{j=1}^m.
\end{equation*}
$$
An important specification is $n$, which acts as the time parameter.
In the above definition, what was "scrambled" was the index associated with each value at time $n$, not $n$ itself.
It is clear therefore (given the structure of $\Sigma_n^{(m)}$) that a temporal permutation, both within the ensemble, and within a specific sample is not invariant: the (ordered) vector[^timeperm]
$$
\begin{equation*}
  (\Sigma_{1}^{(j)},\Sigma_{2}^{(j)},\dots, \Sigma_{n}^{(j)}) \not \deq (\Sigma_{\pi(1)}^{(j)},\Sigma_{\pi(2)}^{(j)},\dots, \Sigma_{\pi(n)}^{(j)}).
\end{equation*}
$$

[^timeperm]: Clearly the distribution of a simple random walk is such that $\Sigma_{n}^{(j)}$ and $\Sigma_{n+k}^{(j)}$ are related, differing only by $\sum_{i=n+1}^{n+k}S_i$; a time dependence. Invariance in permutation of label within a sample, so as to be considered an ensemble, just means that label doesn't affect the distribution (but it might depend on the sample size $m$!). Similarly invariance to permutation to time identifies that time doesn't affect the distribution.

This leads to the question of what *would* it mean for an ensemble to be *invariant to time*?[^notinv]

[^notinv]: a simple random walk is not invariant to time, unless the walk is on a "finite graph"; e.g., a reflected walk with bounds at $\abs{\Sigma_k} = B$ (constraining $\abs{\Sigma_k} \in [B]$ for all $k\in \Z_+$).

If a random variable was invariant to time, each of the ensembles are also:
$$
\begin{equation*}
  (\Sigma_{n}^{(1)},\Sigma_{n}^{(2)},\dots, \Sigma_{n}^{(m)}) \deq (\Sigma_{\pi(n)}^{(1)},\Sigma_{\pi(n)}^{(2)},\dots, \Sigma_{\pi(n)}^{(m)}).
\end{equation*}
$$
A strengthening of this would be an invariance under compositions of single component permutations
$$
\begin{equation*}
  (\Sigma_{n}^{(1)},\Sigma_{n}^{(2)},\dots, \Sigma_{n}^{(m)}) \deq (\Sigma_{\pi(n)}^{(1)},\Sigma_{n}^{(2)},\dots, \Sigma_{n}^{(m)}),
\end{equation*}
$$
into multiple component-wise permutations $\pi_j$
$$
\begin{equation*}
  (\Sigma_{n}^{(1)},\Sigma_{n}^{(2)},\dots, \Sigma_{n}^{(m)}) \deq (\Sigma_{\pi_1(n)}^{(1)},\Sigma_{\pi_2(n)}^{(2)},\dots, \Sigma_{\pi_2(n)}^{(m)}).
\end{equation*}
$$
A further strengthening requires "consistency" of invariance under permutations: we must extend our definition of exchangeability to invariance under permutations $\pi$ of $[\infty]$.

Clearly as mentioned previously, for a simple random walk, for $\pi_n$ a permutation of $[n]$
$$
\begin{equation*}
  (\Sigma_{1}^{(j)},\Sigma_{2}^{(j)},\dots, \Sigma_{n}^{(j)}) \not \deq (\Sigma_{\pi(1)}^{(j)},\Sigma_{\pi(2)}^{(j)},\dots, \Sigma_{\pi(n)}^{(j)}).
\end{equation*}
$$
It is also therefore not invariant under $\pi_\infty$ a permutation of $\infty$.
What is however, are the increments of a simple random walk
$$
\begin{equation*}
  (S_{1}^{(j)},S_{2}^{(j)},\dots, S_{n}^{(j)}) \deq (S_{\pi_\infty(1)}^{(j)},S_{\pi_\infty(2)}^{(j)},\dots, S_{\pi_\infty(n)}^{(j)}).
\end{equation*}
$$
Here, we can also permute the index
$$
\begin{equation*}
  (S_{1}^{(j)},S_{2}^{(j)},\dots, S_{n}^{(j)}) \deq (S_{\pi_\infty(1)}^{(\pi(j))},S_{\pi_\infty(2)}^{(\pi(j))},\dots, S_{\pi_\infty(n)}^{(\pi(j))}).
\end{equation*}
$$
For instance consider a random path $\pr{X_t^{(1)}}_{t\ge 0}$ and an ensemble at an arbitrary time $\tau$, $\cbr{X_\tau^{(j)}}_{j\ge 1}$, where invariance under $\pi_\infty$ holds in both time and label.
Then for bounded functions $f$ (or potentially a larger class)

$$
\begin{equation*}
  \frac{1}{T}\sum_{t=0}^{T-1}f\pr{X_t^{(1)}} \deq \frac{1}{T}\sum_{j=1}^{T}f\pr{X_\tau^{(j)}}.
\end{equation*}
$$
This will be the primary observation of Ergodic Theory, providing conditions for the weaker result that that we might asymptotically (eventually past a certain point in time) the ensemble and temporal are exchangeable, where for all choices of bounded $f$ conditioned on convergence (via the strong law of large numbers)
$$
\begin{equation*}
  \lim_{T\uparrow\infty}\frac{1}{T}\sum_{t=0}^{T}f\pr{X_t^{(1)}} = \lim_{T\uparrow\infty}\frac{1}{T}\sum_{j=0}^{T}f\pr{X_\tau^{(j)}} = \E[f(X_1)], \quad \mathrm{a.s}.
\end{equation*}
$$

## Ergodicity Concepts

Ergodicity gives us tools to relate ensemble and path-wise dynamics, but is the weakest in the mixing hierarchy: $\mathrm{mixing} \implies \mathrm{(weak)mixing} \implies \mathrm{ergodic}$. We will briefly run through relevant definitions, which we sometimes specialize for easy of discussion here.

::: {#def-trans_map}
For a measure space $(\Omega,\mu)$ for $\Omega$ a Banach space and $\mu$ a measure over $\sigma(\Omega)$, we call $T_s : \Omega \rightarrow \Omega$ for $s\in \R_+$ the transform map of a random variable $X_s(\omega)$ for $\omega \in \Omega$ if:

1. $T$ is measure preserving: $\mu(T^{-1}(\Omega)) = \mu(\Omega)$.
2. $T_s$ is measureable for all $s$, i.e. for $A\in \sigma(\Omega)$, $T_s^{-1}(A) \in \sigma(\Omega)$, where we write $(\mu\circ T_s^{-1})(A) = \mu_s(A) = \Pr[X_s \in A]$.
3. $T_s$ admits composition $T_s \circ T_{t} = T_{s+t}$
4. $T_S$ is continuous in $s$, i.e. $\lim_{h\downarrow 0}\norm{T_s - T_{s+h}} =0$
:::

::: {#def-mixing}
We say that $T$, a transform map is (strongly) mixing for measure $\mu$ if 
$$
\begin{equation*}
\lim_{t\uparrow\infty}\mu(A \cap T_t^{-1}(B)) = \mu(A)\mu(B)
\end{equation*}
$$
:::

::: {#def-weakmixing}
We say that $T$, a transform map is weakly mixing for measure $\mu$ if 
$$
\begin{equation*}
\lim_{N\uparrow\infty}\frac{1}{N}\sum_{k=1}^{N}\abs{\mu(A \cap T_k^{-1}(B)) -\mu(A)\mu(B)} = 0
\end{equation*}
$$
:::

::: {#def-ergodic}
We say that $T$, a transform map is ergodic for measure $\mu$ if:

1. $T$ is measure preserving: $\mu(T^{-1}(\Omega)) = \mu(\Omega)$
2. If $J$ is an invariant map of $T$, i.e. $T^{-1}(J) = J$, then $\mu(J) \in \cbr{0,1}$.  
:::

This statement implies that $J$ must be either "essentially" the entire space ($\mu(\Omega) = 1$) or "essentially" nothing ($\mu(\phi) = 0$); in either case the difference between $J$ and the two options is of size or measure zero - e.g. maybe a countable number of points for example.[^fixedpoint]

[^fixedpoint]: This, as already indicated, identifies that once a random variable $X_s \in J$ (associated to our probability measure $\mu_s$), it is in there forever with probability 1: if $\mu(T_s^{-1}J) = 0$ then almost all $X_s$ with probability $1$ are never in $J$ if initialized with distribution $\mu$ (note $T_0$ is the identify map by the continuity assumption). This is just a reiteration of the invariance under the forward map, $\Pr[X_s \in J] = \mu(T_s^{-1}J) = \mu(J)\in \cbr{0,1}$, plus the measure preserving property and definition of ergodicity.

We note that ergodic random variables $X_s$ (those constructed via an ergodic map: $X_{s+t} = T_t (X_s)$), by construction identify $\mu$ as their stationary distribtion, i.e. $\lim_{t\uparrow\infty}\mu \circ T_s^{-1} = \mu$ where instead simply $\mu_s = \mu_t$ for all $s,t\ge 0$. Ergodicity is a stricter form of stationarity (finer). The distiction needed to be made here is the exact initial position $X_s$.

We will assume that $X_0(\omega)=\omega$, i.e. we do not start observing all paths, observable in aggregate with $\mu$, but observe the specific process $\pr{X_s(\omega)}_{s \ge 0}$ with distribution path 
$$
\mu_s^{\omega}\doteq\pr{\mu_s\circ \delta_\omega}_{s \ge 0}
$$
which is *not* stationary. Written this way, it is still deceiving, as the distribution path $\mu_s^{\omega}$ is still about an ensemble given a starting position, not the path $X_s(\omega)$ itself (which may be completely determined by an individual $\omega$).[^nonstat_walk]

[^nonstat_walk]: In the previous section's discussion, we should note that stationarity and ergodicity in time are equivalent to invariance of $(\Sigma_k)_{k\in \Z}$ under displacement in time $T_n(\Sigma_k)_{k\in \Z} = (\Sigma_{k+n})_{k\in \Z} \deq (\Sigma_{k})_{k\in \Z}$.
Here we are again with respect to the simple random walk, with all its other problems, we have a non-stationary process where $\Sigma_0 = 0$, i.e. $\mu_k^{0}$.

The primary observation of Ergodic theory is that there is information about all individual paths observable (measurable) from the ensemble, if we watch the ensemble for a long enough time. Here, we have what is called Birkoff's theorem, indicating that for almost any initialization of $X_s(\omega)$ (with associated measure and ergodic map)
$$
\begin{equation*}
  \lim_{T\uparrow\infty}\frac{1}{T}\sum_{t=0}^{T}f\pr{X_t} = \E[f(X)], \quad \mathrm{a.s}.
\end{equation*}
$$
where $X$ identifies the distributional limit of $X_t$, or rather $X\sim \mu$, for stationary measure $\mu$. Here the identification that this result is almost sure is why this is often called the "Point-wise Ergodic Theorem", which say for almost all but a size 0 set of paths, the time average converges to a deterministic value corresponding to the ensemble average for the function (generalization of law of large numbers). [^initdist]

[^initdist]: That $X\sim \mu$ further stipulates that we cannot look at any ensemble initialized on say $A$, with corresponding measure path $\mu_s^{A}$ but that we also need to wait long enough that $\mu_s^A \approx \mu$. This begs the question of whether the *current* ensemble, potentially as it evolves, is a good representative sample to measure from in order to estimate our paths, as in practice (imagining $A$ as a discrete set of points; a physical population) we estimate
$$
\begin{equation*}
  \frac{1}{T}\sum_{t=0}^{T}f\pr{X_t(\omega)} \approx \frac{1}{T}\sum_{t=0}^{T}\E[f(X_t^A)] \approx \E[f(X)].
\end{equation*}
$$
The stipulation here is that eventually all paths and the ensemble "look" alike, you could even "substitute" one for the other as representative for the same individual at different point in their life.

As an example application (which will lead up to further discussion), consider

$$
N(t,A) = \lambda\{s : X_s \in A, s \in [0,t]\},
$$

understood as the "amount of time, $X_s$ is in $A$" ($\lambda$ is the Lebesgue measure which is just the length of the set in the traditional sense $\lambda [0,t) = t$). Then by Birkoff's we have that

$$
\lim_{t\rightarrow \infty} \frac{N(t,A)}{t} = \Pr[X \in A] = \mu(A),
$$

which says that the amount of time spent in set $A$ is equal to the probability that any path might be in $A$ if we wait long enough (basically forget the limit and approximate).[^ergoinclu] [^informalbirk]

[^ergoinclu]: Under ergodicity, we see that if $\mu(J)= 1$ then $\Pr[X \in A] = \Pr[X \in A \cap J]$. 

[^informalbirk]: An informal, view of Birkoffs essentially indicates that if we scramble time and take the average under permutation (sample time average) and treat it as if it was from an ensemble (sample population average), the usual law of large numbers for sample means holds
$$
\begin{align*}
    \frac{1}{T} \int_{0}^{T} f(X_s)\dd s &\approx \frac{1}{T} \sum_{j=0}^{N-1} f(X_{s_j}) \Delta s_j \\
    &= \frac{1}{T} \sum_{j=0}^{T-1} f(X_{s_{\pi(j)}}) \Delta s_{\pi(j)} \\
    &\approx \E[f(X_1)]
\end{align*}
$$
where $\pi (\cdot)$ is a permutation of all possible rational numbers $s_j \in \Q \cap [0,T]$ (note: we are considering a countably dense set of points), where we may assume for instance that we are taking "finer" partitions as $N\uparrow \infty$; we can just take $\Delta s_i = 1/N$ in the simplest case.

### Extentions of Birkoff

In Ergodic theory, what you can discuss are things called Ergodic Components. Basically say you have spaces $(T,J_1,J_2)$ where these spaces don't connect to one another except from $T \rightarrow J_j$ ($T$ is the "transitive space", basically you eventually leave, unless the process is ugly) and once in $J_j$ you never leave (at least not in probability). These $J_j$ could be absorbing states, or might be richer sets, but at the end of the day, instead of using Birkhoff's in the traditional sense, we can extend this to the Birkhoff-Khinchin which augments Birkhoff as follows[^ergodecomp], again defining $N(t,A) = \lambda\{s : X_s \in A, s \in [0,t]\}$,

[^ergodecomp]: Importantly, any ergodic measure $\mu$ can be represented as a decomposition over its ergodic components, with
$$
\mu = \rho \mu^{J_1} + (1-\rho)\mu^{J_2}
$$
where $\rho = \Pr[X_s \text{ is eventually in } J_1]$ (note: the transient part is missing; there is no $\mu^T$, as with probability $1$ all paths eventually leave $T$). This extends to more general parameterizations, where for ergodic components identified with parameter $\theta \in\Theta$
$$
\mu(A) = \int_\Theta \mu^{\theta}(A) \dd \rho(\theta).
$$


$$ 
\mathbb{E}[f(X)| J_j] = \pr{\lim_{T\rightarrow \infty} \frac{1}{N(T,J_j)} \int_{0}^{T} f(X_s)\mathbb{I}_{X_s \in J_j} \dd s} \quad \text{a.s.}
$$

which complicated expression just indicating that conditioned on being in $J_j$, then Birkhoff holds with $\mu^{J_j}$ (if you're in an Ergodic component $\implies$ you're Ergodic!). This identifies the asymptotic quantity itself as random variables, specifically[^birkoff_Nt]
$$
\begin{align*}
    \lim_{T\rightarrow \infty} \frac{1}{T} \int_{0}^{T} f(X_s)\dd s &= \mathbb{E}[f(X)| J_j] \\
    &\text{w.p} \quad\Pr[X_s \ \text{eventually in } J_j] 
\end{align*}
$$

[^birkoff_Nt]: We remember here that $N(t,A)/t \rightarrow \Pr[X\in A]$. Defining 
$$
\cbr{Y_s : s \in [0,N(T,J_j)]} =\mathrm{Join}\cbr{X_s : X_s \in J_j, s \in [0,T]}
$$ 
as a simply reordering/joining of the process $X_s$ such that that $X_s \in J_j$; which can approximate in as having times $s \in [0,T\Pr[X\in J_j]]$; a change of variables in time induces the same space $[0,T].
By definition, we observe that $\E[f(Y_s)/\Pr[X \in J_j]] = \E[\cbr{X_s | X_s \in J_j}$.
We therefore find the stated fact (in approximation):
$$
\begin{align*}
  \frac{1}{N(T,J_j)} \int_{0}^{T} f(X_s)\mathbb{I}_{X_s \in J_j} \dd s 
  &= \frac{1}{N(T,J_j)} \int_{0}^{N(T,J_j)} f(X_s)\mathbb{I}_{X_s \in J_j} \dd s \dd s \\
  &\approx \frac{1}{T\Pr[X\in J_j]} \int_{0}^{T\Pr[X\in J_j]} f(Y_s) \dd s \\
  &\approx \E[f(X)|\mathcal{I_j}]
\end{align*}
$$

Once I say "any point" Ergodicity tells me that there are an overwelmingly infinite number of points after a large enough $T$ that are essentially indistinguishable from one another (in the grand scheme of things - $L_1$ convergence sense) and therefore this average should look like an ensemble average; getting closer the larger $N$ is as it relates to $T$ (size $T = \lambda[0,T) < \lambda[T,\infty) = \infty, \implies$ "uniform sampling" of points for my average gives $0$ points coming from $[0,T]$ with probability 1).




## Commentary

These prior statements deal with the "long-time" dynamics of this process $f(X_s)$, presuming that the variability of averages are vanishing. In practice however, this observation is just that the error of our time averages is "small enough" after some large time $T$ with respect to our ensemble average and that they are consistent across paths (tending to the same quantity for most paths). 
Essentially, "our estimates are stable and descriptive", and "our estimates apply equally to populations, and as well as across an individuals life": that we may transfer ensemble dynamics to path-wise dynamics.
Ergodicity give us information the properties of path ensembles of paths. This information is not restricted to infinite time as required by Birkhoff ($T\rightarrow\infty)$ but has value also in medium or short (finite) time processes, but depends on how representative the population is for the individual.
How "representative" will depend on the distribution of the ensemble, specifically how close this distribution approximates the stationary distribution.
Temporally, we will care about how long we have observed the individual and the population, asking whether each has had enough time to explore the space; note that if all individuals behave the same, the more coverage we will have (in time and space) of a single individuals life (which we can think of as being approximated by others "close to them" in the population).

In the rest of these notes I will cover some related concepts and at the end include some questions of consideration (either that they were or are being considered by the author). We will begin with a small off-shoot to talking about mixing times, which will attempt to give an answer to "have we watched/measured the individual long enough?" assuming that the population is stationary and the individual dynamic. Afterwards we will discuss the premise of using ergodicity for decisions. Specifically, we will discuss "growth-rate optimality" which is the premise of Ergodicity Economics. This will be the primary (potentially temporary) interest of these notes, attempting to clarify and account for related concepts; as well as being a dumping ground for some superficial analysis.


# Convergence rates and Mixing Times

::: {#def-mixingtime}
We define the $\epsilon > 0$ mixing time for measure $\mu$ as
$$
t_\varepsilon =\inf\cbr{t\ge 0:\sup_{\omega\in \Omega} \sup_{Q\in \Omega} \abs{\mu_t^{\omega}(Q) - \mu(Q)}\le \varepsilon}.
$$
:::

Mixing times are often fairly difficult to work with (having a rather complicated definition, and require sometimes unclear coupling arguments), but they are a useful measure of how quick a distribution $\mu_s^{\omega}$ starting at any point $\omega\in\Omega$ will well approximate the stationary measure $\mu$. Reiterating, this is still about the ensemble, as a measurement of the uniform worst case across ensembles of possible paths. As such it give us, up to discretization error, a good answer to how quickly a population distributed over $A$ with ensemble path distribution $\mu_s^A$ will approximate the stationary distribution $\mu$.[^mixedpos]

[^mixedpos]: Here, if $A\sim \nu$ is a random set (point process), we can represent $\mu_s^A = \nu \mu_{s}^{\omega^A}$ with $\omega^A$ identifying elements of the point process $A$. Here we see that by Jensen's inequality
$$
\begin{align*}
\sup_{Q\in\Omega}\abs{\mu_s^A(Q) - \mu(Q)} 
&\le \E_A \br{\sup_{Q\in\Omega}\abs{\mu_s^{\omega^A}(Q) - \mu(Q)}} \\
&\le \E_A \br{\sup_{\omega\in \Omega} \sup_{Q\in \Omega} \abs{\mu_t^{\omega}(Q) - \mu(Q)}} \\
&= \sup_{\omega\in \Omega} \sup_{Q\in \Omega} \abs{\mu_t^{\omega}(Q) - \mu(Q)}
\end{align*}
$$
and so the mixing time is $\le t_\varepsilon$; again, up to the discretization error treating $A$ as an observed quantity.

How much data we actually have is important, and this $t_\varepsilon$ quantity is saying that only really for $t> t_\varepsilon$ can we consider the observed ensemble a representative sample for the distribution. This still however leaves out the question of how close our specific time average is to the ensemble and population average. To answer this, deliberately non-asymptotically, we need to ask about convergence rates, i.e. for what $r_n\downarrow 0$ 
$$
\abs{\frac{1}{T}\sum_{t=0}^{T}f\pr{X_t} - \E[f(X)]} = O_p\pr{r_T}
$$
and the indicated time $T$ such that this approximation is small enough (say smaller than $\varepsilon>0$). [^empproc]
We are interested here in a study of "large deviations", and bounds such as Chernoff, Hoeffding, etc.
For reversible ergodic markov chains CLT and non-asymtpotic bound exist for the time average. [@Lezaud1998; @Geyer1992]


[^empproc]: Both this expression, and the expression of mixing time, are related to questions about the convergence of the empirical process associated to the random variable; for later it may be interesting to consider uniform LLN/CLT/etc. 

# Growth-rate/Ergodic Transforms

::: {#def-grtrans}
$v:\R_+\times\Omega \rightarrow \Omega$ is the growth-rate transform  of a process $X_t$, if it exists is the one such that $v_t(X_t) = v(t,X_t)$ has ergodic increments $\Delta v_t (X_t)$ 
:::

Note here that to even say "ergodic increments" this implies that we are already considering these increments to be sampled from the associated stationary measure $\mu$; this is not always made formal or clear in discussion. This stationarity further supposes that the "drift" of $\Delta v_t (X_t)$, is constant with respect to time 
$$
\E[\Delta v_t(X_t)|X_t = x] = g(x)
$$
and further supposes that the noise of $\Delta v_t (X_t)$ is stationary (again possibly depending on position, but not time).
We must note again as well that this is an ensemble property, not a path property.

From Ito's lemma[^Ito], in the simplest case of absolute continutity with respect to a brownian motion $B_t$, we are saying that $X_t = f_t(Y_t)$ where $Y_t$ has ergodic increments and
$$
\dd Y_t = g(Y_t)\dd t + \sigma(Y_t)\dd B_t
$$
where therefore we see $v_t$ right inverse of $f_t$. Importantly, but never discussed is that this transform with respect to might $X_t$ might be valid even for $X_t$ with non-stationary growth independent our premised $Y_t$. For instance we may simply consider 
$$
X_t = e^{Y_t - \int_{0}^t \lambda(t)\dd t} \doteq e^{Y_t - \Lambda_t}
$$ 
for non constant $\lambda(t)$.

[^Ito]: Can't figure out how to accent the o.

A specialization of this idea is what is primary considered in Ergodicity Economics.

::: {#def-linearization}
$\ell:\R_+\times\Omega \rightarrow \Omega$ is the linearization of a process $X_t$, if it exists is the one such that $\ell_t(X_t) = \ell(t,X_t)$ has ergodic increments $\Delta v_t (X_t)$ such that $\E[\Delta v_t (X_t)|X_t = x] = g$ where $g$ is a constant.
:::

This heavily simplifes Birkoffs Theorem in the Feller case (strong markov; where this operation in the SDE sense makes sense) into
$$
\lim_{T\uparrow\infty} \frac{1}{T}\int_{0}^T \dd Y_t = \lim_{h\downarrow0}\E\br{\frac{Y_{t+h}-Y_t}{h} \Bigg |Y_t = y } = g.
$$

# Poisson equation and Harmonic transforms

By Ito's lemma finding an ergodic transformation comes down locally, with
$$
\begin{align*}
\dd X_t
&= \xi_t(X_t)\dd t +\rho_t(X_t) \dd B_t
\end{align*}
$$

requires

$$
\begin{align*}
\dd v_t(X_t) 
&= \partial_t v_t(X_t)\dd t +\partial_x v_t(X_t)\dd X_t +  \frac{1}{2}\partial_{x}^2 v_t(X_t) \dd [X,X]_t \\
&= \br{\partial_t v_t(X_t) +\xi_t(x)\partial_x v_t(x) + \frac{1}{2}\partial_{x}^2 v_t(X_t)\rho_t(X_t)^2}\dd t +\partial_x v_t(X_t)\rho_t(X_t)\dd B_t,
\end{align*}
$$

to satisfy[^poisson]

$$
\begin{align*}
g(x) 
&= \br{\partial_t v_t(x) +\xi_t(x)\partial_x v_t(x) + \frac{\rho_t(x)^2}{2}\partial_{x}^2 v_t(x)}\\
\sigma(x)
&=\partial_x v_t(x)\rho_t(x).
\end{align*}
$$
In terms of $v_t$ we write clearly in the second case that
$$
\begin{align*}
\partial_x v_t(x) 
&= \frac{\sigma(x)}{\rho_t(x)}
\end{align*}
$$
which via substitution gives
$$
\begin{align*}
g(x) 
&= \br{\partial_t v_t(x) +\xi_t(x)\partial_x v_t(x)+ \frac{1}{2}\partial_{x}^2 v_t(x)\rho_t(x)^2}\\
&= \br{\partial_t v_t(x) +\frac{\sigma(x)\xi_t(x)}{\rho_t(x)} + \frac{\rho_t(x)^2}{2}\partial_{x}^2\pr{\frac{\sigma(x)}{\rho_t(x)}} }\\
\implies \partial_t v_t(x) 
&= g(x) - \pr{\frac{\sigma(x)\xi_t(x)}{\rho_t(x)} +\xi_t(x) \frac{\rho_t(x)^2}{2}\partial_{x}^2\pr{\frac{\sigma(x)}{\rho_t(x)}}}
\end{align*}
$$

[^poisson]: Note that this is an extension of the Poisson equation for an operator $\calL$ acting on $v_t$, with $\calL v_t = g$.

The format for linearization is similar, simpler, but more strict. Both cases are made simply by no direct $t$ dependence; or at least a known one (for instance consider $X_t e^{\Lambda_t} = e^{Y_t}$).




# Asymptotic Growth-rate Maximization

Still thinking about what to include here. The basic premise of most of Ergodicity Economics is that you should make decisions to maximize the linearized growth rate (see @def-linearization). This only makes sense asymptotically, and if such a linearization exists.


# Finite Time Games

Most games will be structure as the choice between two or more wealth dynamics.
Consider for now simply:

$$
X_s = x_0 e^{Z_t}, \quad Y_t = y_0 e^{W_t}
$$

whose whose rate increments $\Delta Z_t$ and $\Delta W_t$ are ergodic, with stationary increments, having time-averages in expectation $g_X$ and $g_Y$, and where $x_0$ and $y_0$ are initial values of wealth. 

In the short time (I do not force you to play forever), the adminstrator of this game may be able to "grease the wheel" and bribe you into the worse long-run gamble with enough money out-front ($x_0, y_0$). However Asymptotic Growth-Rate Maximization, shortened as AGRM, as would be the recommendation of applying Birkhoff, may give you the wrong answer under finite time horizons.


## Consequence: Ruin under AGRM Indistinguishably

The premise for this section is simple: AGRM does not distinguish between differences in volatility subject to the same asymptotic growth-rate.[^noneqvar]
This is expressly do to the assumption of not finite time horizon; if you play forever, who cares as long as your wealth diverges to infinity.
For now, I can see two work arounds, potentially in combination:

1. Observe the actual physical time horizon.
2. Observe absorbing states in association too, or caused by (lack) of wealth.

The first should be clear, we die eventually even without input. The second is premised on the fact that for instance under most multiplicative games, there is no non-asymptotic absorbing state; under sufficiently poor growth rates you will be penniless (fractions-of-a-fraction of a penny) but, as modeled, will never die due to your wealth.
Incorporating both is simply specifying a morbidity function $Q(t,X_t)$ (the literal survival function for time of death $\tau$, that death $Q(t,X_t)=\Pr[\tau>t|X_t]$) which will depend on the current time and current wealth, which will dictate the probability of death at time $t$.

As a simplification we will for now consider that time alive is valuable without diminishing, and that we would like to maximize it as much as possible. If we wish later to make time less valuable, the clearest way to diminish the worth of time is to diminish the growth rate.[^timedep]


[^timedep]: Less wealth accrued over time, means longer times below a certain level of wealth, leading to increased chance of death for instance.


The problem can therefore be phrase as "maximizing my growth rate for the longest time" which here we simplify as total growth. For a multiplicative gamble this is just

$$
\arg\max\cbr{\log\pr{X_{\tau_1}^{(1)}},\ldots  \log\pr{X_{\tau_{m}}^{(m)}}}
$$
where $\tau_j$ are determined themselves determined by the wealth process $X_{t}^{(j)}$ and the morbidity function $Q(t,X_t^{(j)})$.
If we are to parse $\tau_j$ in terms of expectation, then applying the law of total expectation (condition on the entire path $X_t = x_t$)[^optstop]

$$
\E[\tau_j] = \E\br{\int_0^\infty Q\pr{t,X_t^{(j)}}\dd t}
$$

[^optstop]: This problem seems to be something we might deal with more directly via an optional stopping time for martingales.


[^noneqvar]: Say I give you two processes $X_t=e^{r_X(t)}$ and $Y_t=e^{r_Y(t)}$ with random growth rate increments 
$$
\begin{align}
    r_X(t) &\sim \mathcal{N}(gt,t\sigma_X^2) \\
    r_Y(t) &\sim \mathcal{N}(gt,t\sigma_Y^2).
\end{align}
$$




# One-Time Bets: Stochastic precedence is trivial

We will consider one-time bets under linear and multiplicative growth. The important observation is that you must live with the outcome, and therefore the "game" doesn't truly stop until one dies (a random, finite time horizon).
At a time $\tau$, you are allowed to choose opt-in to the game $G_\tau$. 
In the multiplicative case, under the premise of stochastic precedence, we consider the time $\tau$ relation
$$
\begin{align*}
    \Pr[X_{\tau}^{G} > X_\tau] \doteq \Pr[X_\tau G_\tau > X_\tau],
\end{align*}
$$

Clearly, choose to play if its a favorable bet, i.e. $G_\tau$ is likely greater than $1$.
This criteria does not change even when considering $X_{\tau + T}$,
$$
\begin{align*}
    \Pr[X_{\tau+T}^{G} > X_{\tau +T}] &\doteq \Pr[(X_\tau G_\tau)\frac{X_{\tau+T}}{X_\tau} > X_{\tau+T}] \\
    &= \Pr[ G_\tau> 1]
\end{align*}
$$
Essentially the same result will be true under any additive relation of the bet
$$
\begin{align*}
    \Pr[X_{\tau+T}^{G} > X_{\tau +T}] 
    &\doteq \Pr[(X_\tau + G_\tau)\frac{X_{\tau+T}}{X_\tau} > X_{\tau+T}] \\
    &= \Pr\br{\frac{X_\tau +G_\tau}{X_\tau}>1} \\
    &= \Pr\br{G_\tau>0}
\end{align*}
$$
where, though the decision at first appears relative to your current wealth at time time $\tau$, it is again also trivially a question of whether $G_\tau$ tends to be positive.

## Years gained vs. lost
It's therefore clear that a more comprehensive temporal analysis is needed (this is based off an article whose name I have forgotten). The framing in this section will measure the bet relative to the current dynamics rather than independent of it. A framing for this is "gained/lost time" with respect to ones current wealth and wealth dynamics. Slightly confusing in this section will be the difference between expected and stochastic changes in wealth, and how a human percieves and makes these decisions when converted to time.
Gained/lost years will be measured via the inverse problem of a bet
$$
\begin{align*}
    X_{\tau}^G  
    &= X_\tau + G_\tau \\
    &\doteq X_\tau + \int_{\tau}^{\sigma}\dd X_s = X_{\tau+\sigma}
\end{align*}
$$
where we need to identify $\sigma$ such that
$$
\begin{align*}
   G_\tau
  &\doteq \int_{\tau}^{\sigma}\dd X_s
\end{align*}
$$
and the distribution of $\sigma$.
The simplest dynamics for $X_s$ can be decomposed into a linear and exponential component (cash/"unappreciating" assets, and investments).
For now, we will not deal with these simultaneously (in linear combination); mainly considering the latter case.
In the exponential case, it is straightforward, where we might write
$$
\begin{align*}
   \int_{\tau}^{\sigma}\dd X_s 
   &= X_\tau e^{\mu(\sigma -\tau) + \sqrt{\nu}(B_\sigma - B_\tau)} \\
   \implies \log\pr{\frac{G_\tau}{X_\tau}} + (\mu\tau + \sqrt{\nu}B_\tau) &\deq \mu\sigma + \sqrt{\nu\sigma}B_1
\end{align*}
$$
Where we are distributionally guessing $\sigma$ as the solution to the above equation.
The left hand side is known at time $\tau$, the right is stochastic.
Ignoring that stochastic component due to $B_1$, with $g_\tau = \mu\tau + \sqrt{\nu}B_\tau = \log(X_\tau)$,
$$
\begin{align*}
   \sigma = \frac{1}{\mu}\log\pr{G_\tau} 
\end{align*}
$$
which is clearly just the growth-rate gain if $G_\tau$ is seen as "money from years worked".
This is quite obvious; most of the above calculation was not needed, though maybe informative, I apologize.
A direct calculation gives
$$
\begin{align*}
   \sigma \deq \pr{\frac{\sqrt{\nu}B_1 + \sqrt{\nu B_1^2 + 4\mu\log G_\tau }}{2\mu}}^2
\end{align*}
$$


Under strictly linear growth $X_t = A t + \sqrt{\nu} B_t$, a comparable result can be derived.

<!-- # Ergodic Transforms, Diffusion Processes -->

<!-- I would love to talk about Semi-Martingales in general here, but its a bit involved so for now lets say we consider growth-rates that are diffusion. A diffusion process is a process $X_s$ where -->

<!-- $$ -->
<!-- dX_s = a(X_s) \dd s + b(X_s)dB_t -->
<!-- $$ -->

<!-- where now we allow the drift and diffusion to be a function of the current position. The Ergodic Transform generates increments under the transform $f$, $\Delta f(X_s)$, which are Ergodic. When it exists in the constant drift constant variance sense things are nice, but assuming it doesn't "exactly" is still fine. -->

<!-- The simplest case one could come up with is just that these coefficients for drift and variance converge point-wise in time -->

<!-- $$ -->
<!-- \lim_{t\rightarrow \infty} (a(X_s), b(X_s)) = (\mu, \sigma) \quad a.s. -->
<!-- $$ -->

<!-- This is of course not in general required, as we can instead discuss "dominance" of the dynamics with respect to $T$, i.e. integrating and dividing the process by $T$ we have -->

<!-- $$ -->
<!-- \frac{1}{T} \int_{0}^{T} dX_s =  \frac{1}{T}X_0 + \frac{1}{T} \int_{0}^{T} a(X_s) \dd s + \frac{1}{T} \int_{0}^{T} b(X_s)dB_t -->
<!-- $$ -->

<!-- Then if we let $a = f$ as a nice relabeling to make things familiar to the notation of Birkhoff, we have -->

<!-- $$ -->
<!-- \frac{1}{T} \int_{0}^{T} f(X_s) \dd s = \frac{1}{T} (X_s - X_0) - \frac{1}{T} \int_{0}^{T} b(X_s)dB_t -->
<!-- $$ -->

<!-- which is literally subtracting the "noise" (diffusion part) from the "signal" (drift part). What we have here essentially says that as long as -->

<!-- $$ -->
<!-- \int_{0}^{T} b(X_s)dB_t = o(T) -->
<!-- $$ -->

<!-- i.e.[^gausserror] -->

<!-- $$ -->
<!-- \lim_{T\rightarrow \infty} \frac{1}{T}\int_{0}^{T} b(X_s)dB_t = 0, \quad a.s. -->
<!-- $$ -->

<!-- [^gausserror]:For instance with -->

<!-- $$ -->
<!-- \frac{1}{T}\int b(X_s)dB_t \sim \mathcal{N}\pr{0, \frac{1}{T^2}\int_{0}^{T}\mathbb{E}[b(X_s)^2]\dd s} -->
<!-- $$ -->


<!-- Then in the same sense as Birkhoff and we might write -->

<!-- $$ -->
<!-- \frac{1}{T} (X_s - X_0) \approx \frac{1}{T} \int f(X_s) \dd s + o_p(1) -->
<!-- $$ -->

<!-- i.e. looking at the time average in increments of -->

<!-- $$ -->
<!-- \frac{1}{T}X_s = \frac{1}{T}\sum \Delta X_s -->
<!-- $$ -->

<!-- is just leaves some mean-zero noise around the actual "growth rate". -->

<!-- ## Oops, Wrong Transform! -->

<!-- Now lets say me and my Watson brain, or the random participant in a study doesn't know whats going on, but takes an "educated" guess at the dynamics of the system (going on subconciously in decision making). Then if you allow me the simplification, me assume there truly is an Ergodic Transform. -->
<!-- For instance consider the multiplicative process starting at $X_0 = 1$ with -->

<!-- $$ -->
<!-- X_s = e^{Z_t} -->
<!-- $$ -->

<!-- $$ -->
<!-- d(\log(X_s)) = dZ_t =  \mu \dd s + \sigma dB_t -->
<!-- $$ -->

<!-- Instead of realizing this, us knuckleheads apply what we hoped was the linear transform -->

<!-- $$ -->
<!-- \mathcal{E}_\alpha (X_s) = \varepsilon_\alpha(\log (X_s)). -->
<!-- $$ -->

<!-- Then by It$\hat{\text{o}}$'s formula, -->
<!-- $$ -->
<!-- \begin{align*} -->
<!--     d(\mathcal{E}_\alpha (X_s)) &= d( \varepsilon_\alpha (Z_t)) \\ -->
<!--     &= \partial_x \varepsilon_\alpha (Z_t) dZ_t + \frac{1}{2} \partial_x^2 \varepsilon_\alpha (Z_t)d[Z,Z]_t \\ -->
<!--     &= (\mu \partial_x \varepsilon_\alpha (Z_t) + \frac{\sigma^2}{2} \partial_x^2 \varepsilon_\alpha (Z_t))\dd s + \sigma  \partial_x \varepsilon_\alpha (Z_t) dB_t \\ -->
<!--     &\doteq \mathcal{A}_z \varepsilon_\alpha (Z_t) \dd s + \mathcal{B}_z \varepsilon_\alpha (Z_t) dB_t -->
<!-- \end{align*} -->
<!-- $$ -->

<!-- where to save space we write -->

<!-- $$ -->
<!-- \int_0^T \mathcal{A}_z \varepsilon_\alpha (Z_t) \dd s = \mathbf{A}_T (Z,\alpha) -->
<!-- $$ -->

<!-- and  -->

<!-- $$ -->
<!-- \int_0^T \mathcal{B}_z \varepsilon_\alpha (Z_t) dB_t = \mathbb{M}_T (Z,\alpha). -->
<!-- $$ -->

<!-- This is of course quite bad if $\mathcal{E}_\alpha$ is very far off $\log$. For a simple example lets compare this guessed process to the real one, in probability -->
<!-- $$ -->
<!-- \begin{align*} -->
<!--     \Pr[\mathcal{E}_\alpha (X_s) > Z_t] &= \Pr[\mathbf{A}_t (Z,\alpha) + \mathbb{M}_t (Z,\alpha) > Z_t] \\ -->
<!--     &= \Pr[\mathbf{A}_t (Z,\alpha) + \mathbb{M}_t (Z,\alpha) > \mu t + \sigma B_t] \\ -->
<!--     &= \Pr[\mathbf{A}_t (Z,\alpha) - \mu t > \sigma B_t - \mathbb{M}_t (Z,\alpha)] -->
<!-- \end{align*}. -->
<!-- $$ -->
<!-- The last line is written to suggest that the probability is dictated by "how much" the difference of the drifts is able to overwhelm the noisiness of the data from the diffusion term.  -->

<!-- The problem is now two-fold, the drift can be out-of-wack because of the wrong transform was applied, which leads to rapid increase/decrease in the difference, driving the probability to 1/0. -->
<!-- This would indicate that you feel much better/worse about the processes than you actually should. The same is true for the noise, but more so as it effects the clarity of your perception of reality. -->

<!-- Interesting here is that because of the flexibility you can thing of $(\mathbf{A}_t,\mathbf{B}_t)$ as the participant themselves estimating the drift and diffusion over time, which is an interesting premise to explore especially if you force the participant/gambler to play a game at finite times for a process that in reality is continuous in time (they estimate over increments! $\implies x^{1/t}$ instead of $\log(x)$?). -->

<!-- ## Martingales -->

<!-- I just wanted to reiterate that this can be discussed in more generality, I wrote -->

<!-- $$ -->
<!-- \mathcal{E}_\alpha (X_s) = \mathbf{A}_t (Z,\alpha) + \mathbb{M}_t (Z,\alpha) -->
<!-- $$ -->

<!-- for a reason, the RHS is just how one would write a Semi-Martingale (plus some bits and bobs that are missing in this specific case), more generally the above is the Doob Decomposition of the process $\mathcal{E}_\alpha (X_s)$ -->

<!-- Also very important to mention is that now that we've focused on Ergodic process with Martingale parts, there are many neat tricks for doing calculations (Optional Stopping, Martingale Convergence, Feynman-Kac/Dynkins Formula, etc). -->

<!-- I also would like to note, that an "ergodic transform", is often the equivalent in quantitative finance to a "linearization" as associated to risk-neutral measure. -->









































<!-- # Ranting and other unthoughtful nonsense -->

<!-- , and even processes that are "Ergodicity breaking" such as dynamics under ruin. -->
<!-- We do not live forever, and our enviroments are changing, so asymptotic properties though pleasant may not always be physically meaningful. -->
<!-- This suffers the same problem of assuming "market equilibrium" and "uniform free-trade". -->
<!-- For ergodicity, this assumption is replaced by path-wise stationarity, and infinite time horizons. -->
<!-- It will assume that the forward process $T_s$ is more or less stable, and that "people" do not "meaningfully die". -->
<!-- Both these assumptions are more or less ridiculous, but can be assuaged by approximation: (1) for how long is our process "essentially ergodic"? (2) when making decisions, how does finite time horizon (an "ergodicity-breaking" event; death) pressure individuals to not make "ergodicity optimal" decision? (3) in light of this, what estimates are useful non-asymptotically? (3i) how do we measure approximate ergodicity, in the sense that our estimates are useful in practice? -->

<!-- The main mathematical problem, which I dedicated the above discussion to, was reference for applying Birkhoff's Theorem where some lack of mathematical background seems to have lead some researchers to treating most cases as special cases, sometimes without scrutinizing the inherent problems. This left some feeling that they needed to extend the "theory that is Ergodicity Economics" without practically identifying what needs extension, and whether the current lack of extention might be ignorance of the literature, where I believe we can, through formal treatment, make informed inference based on its foundation, Ergodic Theory. -->
<!-- I have also been particularly concerned with the precedence of Asymptotic Growth-Rate Maximization, where the decision theory element of EE boils down to selecting the process with the larger expected growth rate, rather than analyzing the non-asymptotic behavior, and the path-wise dynamics at a finer level.  -->
<!-- Recognizing the benefit of ergodicity is important, again identifying that we may transfer learning from the ensemble to the individual throughout their life, but there are important questions to be had about how quickly mixing occurs (how quickly this ergodicity actual matters to decsions by/for the particular individual).  -->

<!-- The behavioral element is clear: people make decisions within the dynamics of their environment/existence. What isn't clear is how reasonable asymptotic dynamics are useful in a finite life, and whether humans differentiate the two. What would be interesting here is to allow for mixtures of finite time horizons (random absorption times). Here, conditional on non-absorption, a process may be ergodic (there is the problem of sampling bias; we do not sample the dead to ask how the living are doing, though maybe we sometimes should). Here we should ask whether the mixing time is amenable to the time horizion, so as to judge whether decisions based on substitution of ensemble for time are appropriates; whether we judge our system to be approximately ergodic away from our shelf life. This would potentially connect the many differences in decision making for young people compared to old. -->


<!-- The measure of what is "better-off" has been the primary debate in econcomics leading to utility theory. Standard Ergodicity Economics indicates that a better choice is "long-run growth", a path-wise focus that is tied to an individual rather than a population (if not aggregated and measured over time of course). While this makes many problems more coherent (especially with established results in quantitative finance), it is not clear that it is always an apt description - if I die, what then? - should I not want to die? - should I want others to inherit my riches? - is my goal to make the financial most of myself over my limited time? Each suffers the capitalist imperative that money *is* life, and fails to measure the human. Some work has been done identifying public good as the as a mode consistent with long-run growth (betterment). Similarly the EE framework has been used to demonstrate that cooperation in classical economic examples (one-time bets) which do not admit cooperative equilibrium, by forcing the game to continue. Mathematically this are quite interesting, but anthropologically, it is clear that forcing people to have to live with each other under regulations (rules) admits cooperation; economists would likely even argue that slaves live in cooperation with there masters if not given the means (legislative [rules] or otherwise) to overthrow them. -->
<!-- In any case, many of these cooperative games are often still quite weird, as they focus on corporations (monsters who are premised with a goal of living forever, or causing as much economic turbulence as possible in their demise), or strictly on organizations of public good (who have the actual incentive to be and do good). -->
<!-- This is besides the point, but in all honesty, I would like to see a reasonable economic scenario authentic enough to allow for murder. -->


<!-- ### Problems/Alternatives to stochastic precedence -->
<!-- There are some problems with stochastic precedence, where preferred processes under the probablistic criteria and not inherited (i.e, $X_s \gg Y_s$, $Y_s \gg Z_s$, but $Z_s \gg X_s$), but I think there is a meaningful extension to integrated probabilities and likelihood ratios. -->
<!-- We will talk about this later, but you always have a choice to not play the game offered (even if we break your shins because of it). -->
<!-- Assuming for simplicity that you can go on living your own life, or opt into the game, a simplified premise is that your choice is relative to your current position $N_s$ not to transitions between positions; e.g., "how much better does $X_s$ make me better off compared to $N_s$, and is this more than $Y_s$ makes than $N_s$?". There are problems here too but it is an idea. -->
<!-- Here we can also ask, for what time $\tau$ could my decision "flip" i.e. I would prefer $Y_\tau$ to $X_\tau$. -->

<!-- Another, very path-wise question, is about regret. Not the regret in amount of money that is usually considered by rather an integrated stochastic precedence: -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--     \int_{0}^T \log\Pr[X_s > Y_s] \dd s -->
<!-- \end{equation*} -->
<!-- $$ -->
<!-- In this sense you are really asking, over the betting period, do I prefer my option to the alternative for more of the time (the $\log$ is arbitrary, for instance to emphasize extremes). -->
<!-- We can see this related to the log of the expected amount of time relative to $T$, where we might define  -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--     N_t(X,Y) = \lambda[s: X_s \ge Y_s, s\in [0,t]] -->
<!-- \end{equation*} -->
<!-- $$ -->

<!-- Similarly, the ratio mentioned before is a valid starting point with -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--     \int_{0}^T \log\pr{\frac{\Pr[X_s > r]}{\Pr[Y_s > r]}} \dd s -->
<!-- \end{equation*} -->
<!-- $$ -->
<!-- Again, if $r$ is the point you get killed (or your kneecaps shattered) the primary point is that you choose the option where that doesn't happen. -->
<!-- This is answered more directly by comparing -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--   \Pr[\exists s : X_s < r, s \in [0,t]] -->
<!-- \end{equation*} -->
<!-- $$ -->
<!-- This can similarly be extended to curves -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--   \Pr[\exists s : X_s < r_s, s \in [0,t]] = \Pr[\tau_{r_s} \in [0,t]] -->
<!-- \end{equation*} -->
<!-- $$ -->
<!-- where $\tau_{r_s}$ identifies the the first hitting time of $X_s\in (-\infty,r_s]$ for curve $r_s$. -->
<!-- We can extend this to conditionals given current position, e.g., -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--   \Pr[\exists s : X_s < r_s, s \in [u,t] | \tau_{r_s} > u]. -->
<!-- \end{equation*} -->
<!-- $$ -->
<!-- Where you might get fired from your job for not meeting the required growth (maybe you work as a quant, and they're not gonna keep you on unless you're better than the S&P). -->

<!-- If we are worried about sailing on a barrel full of cement, clearly "ergodicity breaking", this can also be extended to joint probabilities where we consider the time -->
<!-- $$ -->
<!-- \begin{equation*} -->
<!--     N_t(X,Y) = \lambda[s: X_s \ge Y_s, X_s \ge r_s, s\in [0,t]] -->
<!-- \end{equation*} -->
<!-- $$ -->


<!-- ## Ergodic Transform in Finite time -->

<!-- We will now consider the Ergodic transform under multiplicative dynamics on $X_s$ i.e. in probability as per Stochastic Precedence -->
<!-- $$ -->
<!-- \begin{align*} -->
<!--     \Pr[X_T > Y_T] &= \Pr[\frac{1}{T}\log (\frac{X_T}{X_0}) > \frac{1}{T}\log (\frac{Y_T}{Y_0})] \\ -->
<!--     &= \Pr[\frac{1}{T}Z_T > \frac{1}{T}W_T + \frac{1}{T}\log (\frac{y_0}{x_0})] \\ -->
<!--     &= \Pr[\bar{g}_{T}^{X} > \bar{g}_{T}^{Y} + \frac{1}{T}\log (\frac{y_0}{x_0})] \\ -->
<!--     &\doteq \Pr[\bar{g}_{T}^{X} > \bar{g}_{T}^{Y} + \gamma_T ] -->
<!-- \end{align*} -->
<!-- $$ -->
<!-- what we see here is that we are once again comparing "relatively stable" processes, the average growth rate, and some bias attributed to the initial wealth.  -->

<!-- If $X_s = Y_T$, the sign of $\gamma_T$ selects in probability the better process if we make our decision as whether -->

$$
\Pr[\bar{g}_{T}^{X} > \bar{g}_{T}^{Y} + \gamma_T ] > \frac{1}{2}
$$

or not.

<!-- ## Remarks -->
<!-- ### First -->
<!-- Quick first remark, remembering Birkhoff -->

<!-- $$ -->
<!-- \mathbb{E}[f(X)] = \lim_{T\rightarrow \infty} \frac{1}{T} \int_{0}^{T} f(X_s)\dd s \quad \text{a.s.} -->
<!-- $$ -->

<!-- note that I didn't care what $Z_t$ or $W_t$ looked like, all I did was say it was Ergodic, not that it was a stationary independent increment Brownian motion with constant drift and diffusion as many papers have assumed for simplicity. No need for "niceness" like -->

<!-- $$ -->
<!-- dX_s = a \dd s + b dB_t, \quad a,b \in \mathbb{R}, -->
<!-- $$ -->

<!-- this is just a very special case that makes calculations easy, and is actually quite restrictive. -->

<!-- ### Second -->
<!-- Second, AGRM in either case "nice" or not, is implied by Stochastic precedence. Consider once again -->

<!-- $$ -->
<!-- \Pr[\bar{g}_{T}^{X} > \bar{g}_{T}^{Y} + \gamma_T ] -->
<!-- $$ -->

<!-- Birkhoff says that as the limit is in the almost sure sense we have that -->
<!-- $$ -->
<!-- \begin{align*} -->
<!--     \Pr[\lim_{T\rightarrow \infty}\{\bar{g}_{T}^{X} > \bar{g}_{T}^{Y} + \gamma_T \}] &= \Pr[\bar{g}_{\infty}^{X} > \bar{g}_{\infty}^{Y}] \\ -->
<!--     &= \Pr[g_{X} > g_{Y}] \in \{0,1\} -->
<!-- \end{align*} -->
<!-- $$ -->

<!-- the only worry one may have is when $g_X = g_Y$, which is an infinite-time/limit issue that's a great segway into the next section, ruin! -->



